Create table COMPTE
(
    NUM_CAND	    INT(4),
    LOGIN           VARCHAR(25) UNIQUE,
    EMAIL           VARCHAR(25) NOT NULL,
    NOM             VARCHAR(25) NOT NULL,
    PRENOM          VARCHAR(25) NOT NULL,
    SEXE	    CHAR(1),
    MOT_DE_PASSE    VARCHAR(50) NOT NULL,
    CANDIDAT	    CHAR(1),
    BLACKLIST	    CHAR(1),
    CHECK(SEXE IN('M','F') ),
    CHECK(CANDIDAT IN('Y','N') ),
    CHECK(BLACKLIST IN('Y','N') ),
    PRIMARY KEY(NUM_CAND)
);

Create table CONTACTS
(
    NUM_CONTACT		INT(4),
    EMAIL		VARCHAR(25)      NOT NULL,
    NOM			VARCHAR(25)      NOT NULL,
    PRENOM		VARCHAR(25)      NOT NULL,
    COMMENTAIRE		VARCHAR(250) NOT NULL,
    PRIMARY KEY(NUM_CONTACT)
);

Create table OFFRES
(
    NUM_OFFRE		  INT(4),
    NOM_POSTE         VARCHAR(25) NOT NULL,
    LIEU_TRAVAIL      VARCHAR(25) NOT NULL,
    TYPE_EMPLOI	      VARCHAR(25) NOT NULL,
    DIPLOME		      VARCHAR(10) NOT NULL,
    MISSION		      VARCHAR(250) NOT NULL,
    PRIMARY KEY(NUM_OFFRE)
);
