Create table CANDIDATS
(
    NUM_CAND	    NUMBER(4),
    LOGIN	    VARCHAR2(25),
    EMAIL           VARCHAR2(25),
    NOM             VARCHAR2(25),
    PRENOM          VARCHAR2(25),
    SEXE	    CHAR(1),
    MOT_DE_PASSE    VARCHAR2(14),
    CONSTRAINT PK_CANDIDATS			PRIMARY KEY(NUM_CAND),
    CONSTRAINT LOGIN				UNIQUE(LOGIN),
    CONSTRAINT NN_CANDIDATS_NOM			CHECK(NOM IS NOT NULL),
    CONSTRAINT NN_CANDIDATS_PRENOM		CHECK(PRENOM IS NOT NULL),
    CONSTRAINT NN_CANDIDATS_MOT_DE_PASSE	CHECK(MOT_DE_PASSE IS NOT NULL),
    CONSTRAINT CK_CANDIDATS_SEXE		CHECK(SEXE IN('F','M'))
);

Create table CONTACTS
(
    NUM_CONTACT		NUMBER(4),
    EMAIL		VARCHAR2(25),
    NOM			VARCHAR2(25),
    PRENOM		VARCHAR2(25),
    COMMENTAIRE		VARCHAR2(250),
    CONSTRAINT PK_CONTACTS		PRIMARY KEY(NUM_CONTACT),
    CONSTRAINT NN_CONTACTS_EMAIL	CHECK(EMAIL IS NOT NULL),
    CONSTRAINT NN_CONTACTS_NOM		CHECK(NOM IS NOT NULL),
    CONSTRAINT NN_CONTACTS_PRENOM	CHECK(PRENOM IS NOT NULL),
    CONSTRAINT NN_CONTACTS_COMMENTAIRE	CHECK(COMMENTAIRE IS NOT NULL)
);

Create table OFFRES
(
    NUM_OFFRE		  NUMBER(4),
    NOM_POSTE             VARCHAR2(25),
    LIEU_TRAVAIL          VARCHAR2(25),
    TYPE_EMPLOI	          VARCHAR2(25),
    DIPLOME		  VARCHAR2(10),
    MISSION		  VARCHAR2(250),
    CONSTRAINT PK_OFFRES			PRIMARY KEY(NUM_OFFRE),
    CONSTRAINT NN_OFFRES_NOM_POSTE		CHECK(NOM_POSTE IS NOT NULL),
    CONSTRAINT NN_OFFRES_LIEU_TRAVAIL	CHECK(LIEU_TRAVAIL IS NOT NULL),
    CONSTRAINT NN_OFFRES_TYPE_EMPLOI		CHECK(TYPE_EMPLOI IS NOT NULL),
    CONSTRAINT NN_OFFRES_DIPLOME		CHECK(DIPLOME IS NOT NULL),
    CONSTRAINT NN_OFFRES_MISSION		CHECK(MISSION IS NOT NULL)
);
