CREATE TABLES CANDIDATS
(
    NUM_CAND	    NUMBER(4),
    EMAIL           VARCHAR2(25),
    NOM             VARCHAR2(25),
    PRENOM          VARCHAR2(25),
    SEXE	    CHAR(1),
    MOT_DE_PASSE    VARCHAR2(25),
    CONSTRAINT PK_CANDIDATS            PRIMARY KEY(NUM_CAND),
    CONSTRAINT NN_CANDIDATS_NOM        CHECK(NOM IS NOT NULL),
    CONSTRAINT NN_CANDIDATS_PRENOM     CHECK(PRENOM IS NOT NULL),
    CONSTRAINT NN_CANDIDATS_MOT_DE_PASSE CHECK(MOT_DE_PASSE IS NOT NULL),
    CONSTRAINT CK_CANDIDATS_SEXE     CHECK(SEXE IN('F','M'))
);

CREATE TABLES CONTACTS
(
    NUM_CONTACTS    NUMBER(4),
    EMAIL           VARCHAR2(25),
    NOM             VARCHAR2(25),
    PRENOM          VARCHAR2(25),
    COMMENTAIRE	    VARCHAR(250),
    CONSTRAINT PK_CANDIDATS            PRIMARY KEY(NUM_CONTACTS),
    CONSTRAINT NN_CANDIDATS_EMAIL      CHECK(EMAIL IS NOT NULL),
    CONSTRAINT NN_CANDIDATS_NOM        CHECK(NOM IS NOT NULL),
    CONSTRAINT NN_CANDIDATS_PRENOM     CHECK(PRENOM IS NOT NULL),
    CONSTRAINT NN_CANDIDATS_COMMENTAIRE CHECK(COMMENTAIRE IS NOT NULL)
);


CREATE TABLES OFFRES
(
    NUM_OFFRES 		  NUMBER(4),
    NOM_POSTE             VARCHAR2(25),
    LIEU_TRAVAIL          VARCHAR2(25),
    TYPE_EMPLOI	          VARCHAR2(25),
    DIPLOME		  VARCHAR(10),
    MISSION		  VARCHAR2(250),
    CONSTRAINT PK_CANDIDATS            PRIMARY KEY(NUM_OFFRES),
    CONSTRAINT NN_CANDIDATS_NOM_POSTE      CHECK(NOM_POSTE IS NOT NULL),
    CONSTRAINT NN_CANDIDATS_LIEU_TRAVAIL        CHECK(LIEU_TRAVAIL IS NOT NULL),
    CONSTRAINT NN_CANDIDATS_TYPE_EMPLOI     CHECK(TYPE_EMPLOI IS NOT NULL),
    CONSTRAINT NN_CANDIDATS_DIPLOME CHECK(DIPLOME IS NOT NULL),
    CONSTRAINT NN_CANDIDATS_MISSION CHECK(MISSION IS NOT NULL)
);